spring:
  #  mvc:
  #    # 静态资源的特定访问前缀，该配置会影响欢迎页与网站图标显示
  #    static-path-pattern: /res/**
  web:
    resources:
      # 指定静态资源访问文件夹
      static-locations: [ classpath:/abc/ ]
      # 禁用所有静态资源
  #      add-mappings: false

  mvc:
    hiddenmethod:
      filter:
        # 开启页面form表单提交restFull风格请求方式
        enabled: true
