server:
  port: 9093
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # 修改dispatcherServlt处理的路径，默认拦截 / 路径
  #  mvc:
  #    servlet:
  #      path: /mvc

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sasa
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=true
    #    type: com.alibaba.druid.pool.DruidDataSource
    # 引入druid-stater后可以对监控页面上的功能一配置文件的形式进行控制
    druid:
      # 开启spring的监控功能
      aop-patterns: com.lzw.web.*

      # 开启页面监控，设置登录名、密码
      stat-view-servlet:
        enabled: true
        login-username: a
        login-password: a
      #加入过滤器,sql监控功能与防火墙
      filters: stat,wall
      #过滤器中的详细配置
      filter:
        wall:
          enabled: true
          # 不允许删表
          config:
            drop-table-allow: false
        stat:
          enabled: true
          # 超过多少毫秒为慢sql
          slow-sql-millis: 10000
      # 开启web监控
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

mybatis:
  # mybatis全局配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  # mapper文件映射地址
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名，对于属性配置，如果指定了 config-location 的路径，则必须再指定的配置文件里配置，否则会冲突
#  configuration:
#    map-underscore-to-camel-case: true
