spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sasa
    url: jdbc:mysql://127.0.0.1:3306/test?userSSL=false

logging:
  level:
    com.lzw: debug
mybatis-plus:
  configuration:
    # 控制在控制台打印日志默认实现类是 org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
